EquiforestWebApp/Models/Contenedores.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EquiforestWebApp.Models
{
    public class Contenedores
    {
        public int Id { get; set; }
        public DateTime FechaSalida { get; set; }
        [MaxLength(20)]
        public string ContenedorId { get; set; }
        [MaxLength(10)]
        public string Cabezal { get; set; }
        [MaxLength(10)]
        public string Sello { get; set; }
        [MaxLength(30)]
        public string Chofer { get; set; }
        public float DescuentoCrc { get; set; }
        public float DescuentoLong { get; set; }
        public float MaxCargoWgt { get; set; }
        [MaxLength(10)]
        public string FacturaId { get; set; }
        [MaxLength(30)]
        public string PackingListId { get; set; }
        [ForeignKey("FacturaId")]
        public Facturas Factura { get; set; }
        
    }
}

EquiforestWebApp/Controllers/ContenedoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EquiforestWebApp.Data;
using EquiforestWebApp.Models;

namespace EquiforestWebApp.Controllers
{
    public class ContenedoresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ContenedoresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Contenedores
        public async Task<IActionResult> Index(int? pageNumber, DateTime fecini, DateTime fecfin)
        {
            int pageSize = 10;
            var _fecini = fecini.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1) : fecini.Date;
            var _fecfin = fecfin.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)) : fecfin.Date;
            ViewData["FecIni"] = _fecini.ToString("yyyy-MM-dd");
            ViewData["FecFin"] = _fecfin.ToString("yyyy-MM-dd");
            //return View(await _context.Facturas.ToListAsync());
            return View(await PaginatedList<Contenedores>.CreateAsync(_context.Contenedores.Include(t => t.Factura).Where(f => f.FechaSalida >= _fecini && f.FechaSalida <= _fecfin).AsNoTracking(), pageNumber ?? 1, pageSize));

            //var applicationDbContext = _context.Contenedores.Include(c => c.Factura);
            //return View(await applicationDbContext.ToListAsync());
        }

        // GET: Contenedores/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contenedores = await _context.Contenedores
                .Include(c => c.Factura)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (contenedores == null)
            {
                return NotFound();
            }

            return View(contenedores);
        }

        // GET: Contenedores/Create
        public IActionResult Create()
        {
            ViewData["FacturaId"] = new SelectList(_context.Facturas, "FacturaId", "FacturaId");
            return View();
        }

        // POST: Contenedores/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,FechaSalida,ContenedorId,Cabezal,Sello,Chofer,DescuentoCrc,DescuentoLong,MaxCargoWgt,FacturaId,PackingListId")] Contenedores contenedores)
        {
            if (ModelState.IsValid)
            {
                _context.Add(contenedores);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacturaId"] = new SelectList(_context.Facturas, "FacturaId", "FacturaId", contenedores.FacturaId);
            return View(contenedores);
        }

        // GET: Contenedores/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contenedores = await _context.Contenedores.SingleOrDefaultAsync(m => m.Id == id);
            if (contenedores == null)
            {
                return NotFound();
            }
            ViewData["FacturaId"] = new SelectList(_context.Facturas, "FacturaId", "FacturaId", contenedores.FacturaId);
            return View(contenedores);
        }

        // POST: Contenedores/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FechaSalida,ContenedorId,Cabezal,Sello,Chofer,DescuentoCrc,DescuentoLong,MaxCargoWgt,FacturaId,PackingListId")] Contenedores contenedores)
        {
            if (id != contenedores.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(contenedores);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContenedoresExists(contenedores.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["FacturaId"] = new SelectList(_context.Facturas, "FacturaId", "FacturaId", contenedores.FacturaId);
            return View(contenedores);
        }

        // GET: Contenedores/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contenedores = await _context.Contenedores
                .Include(c => c.Factura)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (contenedores == null)
            {
                return NotFound();
            }

            return View(contenedores);
        }

        // POST: Contenedores/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contenedores = await _context.Contenedores.SingleOrDefaultAsync(m => m.Id == id);
            _context.Contenedores.Remove(contenedores);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContenedoresExists(int id)
        {
            return _context.Contenedores.Any(e => e.Id == id);
        }
    }
}

EquiforestWebApp/Views/Contenedores/Create.cshtml
@model EquiforestWebApp.Models.Contenedores

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Contenedores</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FechaSalida" class="control-label"></label>
                <input asp-for="FechaSalida" class="form-control" />
                <span asp-validation-for="FechaSalida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContenedorId" class="control-label"></label>
                <input asp-for="ContenedorId" class="form-control" />
                <span asp-validation-for="ContenedorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cabezal" class="control-label"></label>
                <input asp-for="Cabezal" class="form-control" />
                <span asp-validation-for="Cabezal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sello" class="control-label"></label>
                <input asp-for="Sello" class="form-control" />
                <span asp-validation-for="Sello" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Chofer" class="control-label"></label>
                <input asp-for="Chofer" class="form-control" />
                <span asp-validation-for="Chofer" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescuentoCrc" class="control-label"></label>
                <input asp-for="DescuentoCrc" class="form-control" />
                <span asp-validation-for="DescuentoCrc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescuentoLong" class="control-label"></label>
                <input asp-for="DescuentoLong" class="form-control" />
                <span asp-validation-for="DescuentoLong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxCargoWgt" class="control-label"></label>
                <input asp-for="MaxCargoWgt" class="form-control" />
                <span asp-validation-for="MaxCargoWgt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FacturaId" class="control-label"></label>
                <select asp-for="FacturaId" class ="form-control" asp-items="ViewBag.FacturaId"></select>
            </div>
            <div class="form-group">
                <label asp-for="PackingListId" class="control-label"></label>
                <input asp-for="PackingListId" class="form-control" />
                <span asp-validation-for="PackingListId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EquiforestWebApp/Views/Contenedores/Delete.cshtml
@model EquiforestWebApp.Models.Contenedores

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contenedores</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContenedorId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContenedorId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cabezal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cabezal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sello)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sello)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Chofer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Chofer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DescuentoCrc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescuentoCrc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DescuentoLong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescuentoLong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaxCargoWgt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaxCargoWgt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PackingListId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PackingListId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Factura)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Factura.FacturaId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EquiforestWebApp/Views/Contenedores/Details.cshtml
@model EquiforestWebApp.Models.Contenedores

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Contenedores</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.FechaSalida)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaSalida)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ContenedorId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ContenedorId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cabezal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cabezal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Sello)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Sello)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Chofer)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Chofer)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DescuentoCrc)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescuentoCrc)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DescuentoLong)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DescuentoLong)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaxCargoWgt)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.MaxCargoWgt)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.PackingListId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PackingListId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Factura)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Factura.FacturaId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EquiforestWebApp/Views/Contenedores/Edit.cshtml
@model EquiforestWebApp.Models.Contenedores

@{
    ViewData["Title"] = "Editar Contenedores";
}

<h2>Editar</h2>

<h4>Contenedores</h4>
<hr />
<div class="row">
    <form asp-action="Edit">
        <div class="col-md-4">

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="FechaSalida" class="control-label">Fecha de Salida</label>
                <input asp-for="FechaSalida" class="form-control" />
                <span asp-validation-for="FechaSalida" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContenedorId" class="control-label">Contenedor</label>
                <input asp-for="ContenedorId" class="form-control" />
                <span asp-validation-for="ContenedorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cabezal" class="control-label"></label>
                <input asp-for="Cabezal" class="form-control" />
                <span asp-validation-for="Cabezal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sello" class="control-label"></label>
                <input asp-for="Sello" class="form-control" />
                <span asp-validation-for="Sello" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Chofer" class="control-label"></label>
                <input asp-for="Chofer" class="form-control" />
                <span asp-validation-for="Chofer" class="text-danger"></span>
            </div>
        </div>
        <div class="col-md-4">
                <div class="form-group">
                    <label asp-for="DescuentoCrc" class="control-label">Descuento Circ.</label>
                    <input asp-for="DescuentoCrc" class="form-control" />
                    <span asp-validation-for="DescuentoCrc" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="DescuentoLong" class="control-label">Descuento Long.</label>
                    <input asp-for="DescuentoLong" class="form-control" />
                    <span asp-validation-for="DescuentoLong" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="MaxCargoWgt" class="control-label">Max Cargo Wgt.</label>
                    <input asp-for="MaxCargoWgt" class="form-control" />
                    <span asp-validation-for="MaxCargoWgt" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="FacturaId" class="control-label">Factura</label>
                    <select asp-for="FacturaId" class="form-control" asp-items="ViewBag.FacturaId">
                        <option selected="selected" value="@Model.FacturaId">Seleccionar la factura</option>
                    </select>
                    <span asp-validation-for="FacturaId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PackingListId" class="control-label">Packing List</label>
                    <input asp-for="PackingListId" class="form-control" />
                    <span asp-validation-for="PackingListId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Guardar" class="btn btn-default" />
                </div>

        </div>
</form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EquiforestWebApp/Views/Contenedores/Index.cshtml
@model PaginatedList<EquiforestWebApp.Models.Contenedores>

@{
    ViewData["Title"] = "Lista de Contenedores";
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0px";
    }
</script>

<div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a asp-controller="Facturas" asp-action="Index">Facturas</a>
    <a asp-controller="Contenedores" asp-action="Index">Contenedores</a>
    <a asp-controller="Facturas" asp-action="PackingList" asp-route-origen="2">Packing List</a>
</div>

<h4><span style="font-size:20px;cursor:pointer" onclick="openNav()">&#9776; Comercializacion</span></h4>

<h2>Lista de Contenedores</h2>

<div class="col-md-6 col-xs-4">
    <form asp-controller="Contenedores" asp-action="Index" method="get">
        <div class="form form-inline">
            <p>
                <input type="hidden" name="pageNumber" value="1" />
                <input type="date" class="form-control" name="fecini" value="@ViewData["FecIni"]" />
                <input type="date" class="form-control" name="fecfin" value="@ViewData["FecFin"]" />
                <input type="submit" value="Filtrar" class="btn btn-default" />
            </p>
        </div>
    </form>
</div>

<p>
    <a asp-action="Create" class="btn btn-info">Crear Contenedor</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                Fecha Salida
            </th>
            <th>
                Contenedor
            </th>
            <th>
                Cabezal
            </th>
            <th>
                Sello
            </th>
            <th>
                Chofer
            </th>
            <th>
                Desc. Circ.
            </th>
            <th>
                Desc. Long.
            </th>
            <th>Max. Cargo Wgt.</th>
            <th>
                Packing List
            </th>
            <th>
                Factura
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.FechaSalida.ToShortDateString()
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ContenedorId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cabezal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sello)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Chofer)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DescuentoCrc)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DescuentoLong)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MaxCargoWgt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PackingListId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Factura.FacturaId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    @*<a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>*@
                </td>
            </tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-fecini="@ViewData["FecIni"]"
       asp-route-fecfin="@ViewData["FecFin"]"
       class="btn btn-default @prevDisabled">
        Previous
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-fecini="@ViewData["FecIni"]"
       asp-route-fecfin="@ViewData["FecFin"]"
       class="btn btn-default @nextDisabled">
        Next
    </a>

</div>