EquiforestWebApp/Models/Viajes.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace EquiforestWebApp.Models
{
    public class Viajes
    {
        public int Id { get; set; }
        [Column(TypeName = "varchar(30)")]
        public string ViajeId { get; set; }
        [Required]
        public string Nucleo { get; set; }
        [Required]
        public string Finca { get; set; }
        [Required]
        public string Rodal { get; set; }
        [Required]
        [DataType(DataType.Date)]
        public DateTime FechaIngreso { get; set; }
        [Required]
        public string Ubicacion { get; set; }
        [Required]
        public int? N_Viaje { get; set; }
        public int? NoTrozasC { get; set; }

        public List<Trozas> Trozas { get; set; }
        [NotMapped]
        public List<SelectListItem> Nucleos { get; set; }
        [NotMapped]
        public List<SelectListItem> Fincas { get; set; }
        [NotMapped]
        public List<SelectListItem> Rodales { get; set; }
    }
}

EquiforestWebApp/Controllers/ViajesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EquiforestWebApp.Data;
using EquiforestWebApp.Models;
using Microsoft.AspNetCore.Http;
using OfficeOpenXml;
using System.IO;
using System.Web;

namespace EquiforestWebApp.Controllers
{
    public class ViajesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ViajesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Viajes
        public async Task<IActionResult> Index(int? pageNumber, DateTime fecini, DateTime fecfin, bool download, string rodal)
        {
            int pageSize = 15;
            var _fecini = fecini.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1) : fecini.Date;
            var _fecfin = fecfin.Year < 1900 ? new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.DaysInMonth(DateTime.Now.Year, DateTime.Now.Month)) : fecfin.Date;
            ViewData["FecIni"] = _fecini.ToString("yyyy-MM-dd");
            ViewData["FecFin"] = _fecfin.ToString("yyyy-MM-dd");

            List<ViajesGroup> viajesgroupList = new List<ViajesGroup>();
            if (rodal==null)
            {
                var result = from s in _context.Viajes
                             join t in _context.Trozas
                             on s.ViajeId equals t.ViajeId into joinViajes
                             where s.FechaIngreso >= _fecini && s.FechaIngreso <= _fecfin
                             from tr in joinViajes.DefaultIfEmpty()
                             select new
                             {
                                 Nucleo = s.Nucleo,
                                 Finca = s.Finca,
                                 Rodal = s.Rodal,
                                 Fecha = s.FechaIngreso,
                                 Ubicacion = s.Ubicacion,
                                 N_Viaje = (int)s.N_Viaje,
                                 NoTrozasC = s.NoTrozasC,
                                 Clasificacion = tr == null ? "" : tr.Clasificacion,
                                 Circunferencia = tr == null ? 0f : tr.Circunferencia,
                                 Longitud = tr == null ? 0f : tr.Largo,
                                 Volumen = tr == null ? 0f : MathF.Round((float)(((tr.Circunferencia * tr.Circunferencia) / (4 * Math.PI)) * tr.Largo / 10000), 2)
                             };
                var viajesgroupresult = result.OrderBy(o => o.Fecha).ThenBy(o => o.N_Viaje).ThenBy(o => o.Clasificacion).GroupBy(g => new { g.Nucleo, g.Finca, g.Rodal, g.Fecha, g.Ubicacion, g.N_Viaje, g.Clasificacion });
                foreach (var viaje in viajesgroupresult)
                {
                    viajesgroupList.Add(new ViajesGroup
                    {
                        Nucleo = viaje.Key.Nucleo,
                        Finca = viaje.Key.Finca,
                        Rodal = viaje.Key.Rodal,
                        Fecha = viaje.Key.Fecha,
                        Ubicacion = viaje.Key.Ubicacion,
                        N_Viaje = viaje.Key.N_Viaje,
                        Clasificacion = viaje.Key.Clasificacion,
                        Circunferencia = viaje.Average(c => c.Circunferencia),
                        Longitud = viaje.Average(l => l.Longitud),
                        Cantidad = viaje.Sum(v => v.Volumen) > 0 ? viaje.Count() : 0,
                        Volumen = viaje.Sum(v => v.Volumen),
                        NoTrozasC = viaje.Max(t => t.NoTrozasC)
                    });
                }
            } else
            {
                var result = from s in _context.Viajes
                             join t in _context.Trozas
                             on s.ViajeId equals t.ViajeId into joinViajes
                             where s.FechaIngreso >= _fecini && s.FechaIngreso <= _fecfin && s.Rodal == rodal
                             from tr in joinViajes.DefaultIfEmpty()
                             select new
                             {
                                 Nucleo = s.Nucleo,
                                 Finca = s.Finca,
                                 Rodal = s.Rodal,
                                 Fecha = s.FechaIngreso,
                                 Ubicacion = s.Ubicacion,
                                 N_Viaje = (int)s.N_Viaje,
                                 NoTrozasC = s.NoTrozasC,
                                 Clasificacion = tr == null ? "" : tr.Clasificacion,
                                 Circunferencia = tr == null ? 0f : tr.Circunferencia,
                                 Longitud = tr == null ? 0f : tr.Largo,
                                 Volumen = tr == null ? 0f : MathF.Round((float)(((tr.Circunferencia * tr.Circunferencia) / (4 * Math.PI)) * tr.Largo / 10000), 2)
                             };
                var viajesgroupresult = result.OrderBy(o => o.Fecha).ThenBy(o => o.N_Viaje).ThenBy(o => o.Clasificacion).GroupBy(g => new { g.Nucleo, g.Finca, g.Rodal, g.Fecha, g.Ubicacion, g.N_Viaje, g.Clasificacion });
                foreach (var viaje in viajesgroupresult)
                {
                    viajesgroupList.Add(new ViajesGroup
                    {
                        Nucleo = viaje.Key.Nucleo,
                        Finca = viaje.Key.Finca,
                        Rodal = viaje.Key.Rodal,
                        Fecha = viaje.Key.Fecha,
                        Ubicacion = viaje.Key.Ubicacion,
                        N_Viaje = viaje.Key.N_Viaje,
                        Clasificacion = viaje.Key.Clasificacion,
                        Circunferencia = viaje.Average(c => c.Circunferencia),
                        Longitud = viaje.Average(l => l.Longitud),
                        Cantidad = viaje.Sum(v => v.Volumen) > 0 ? viaje.Count() : 0,
                        Volumen = viaje.Sum(v => v.Volumen),
                        NoTrozasC = viaje.Max(t => t.NoTrozasC)
                    });
                }
            }


            
            
            
            //return View(await _context.Trozas.ToListAsync());
            if (download)
            {
                Download(viajesgroupList,"Viajes.xlsx");
            }
            ViewData["Rodales"] = GetRodales();
            ViewData["RodalSelected"] = rodal;
            return View(PaginatedList<ViajesGroup>.Create(viajesgroupList.AsQueryable(), pageNumber ?? 1, pageSize));
            //return View(await PaginatedList<Trozas>.CreateAsync(_context.Trozas.Include(t => t.Viaje).Where(f => f.Viaje.FechaIngreso >= _fecini && f.Viaje.FechaIngreso <= _fecfin).AsNoTracking(), pageNumber ?? 1, pageSize));

            //return View(await _context.Viajes.ToListAsync());
        }

        // GET: Viajes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var viajes = await _context.Viajes
                .SingleOrDefaultAsync(m => m.ViajeId == id);
            if (viajes == null)
            {
                return NotFound();
            }

            return View(viajes);
        }

        // GET: Viajes/Create
        public IActionResult Create()
        {
            //GetSelectedListItem();
            return View();
        }

        // POST: Viajes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nucleo,Finca,Rodal,FechaIngreso,Ubicacion,N_Viaje")] Viajes viajes)
        {
            viajes.ViajeId = viajes.Rodal + viajes.N_Viaje.ToString() + viajes.FechaIngreso.Month.ToString() + "/" + viajes.FechaIngreso.Day.ToString() + "/" + viajes.FechaIngreso.Year.ToString();

            if (ModelState.IsValid)
            {
                _context.Add(viajes);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(viajes);
        }

        public IActionResult OnGetViajesCreate(int id)
        {
            //GetSelectedListItem();
            var model = new Viajes();
            model.Nucleos = GetNucleos();
            model.Fincas = GetFincas();
            model.Rodales = GetRodales();
            return PartialView("/Views/Viajes/_ViajesCreate.cshtml", model);
        }

        public async Task<IActionResult> OnPostViajesCreate([Bind("Nucleo,Finca,Rodal,FechaIngreso,Ubicacion,N_Viaje")] Viajes viajes)
        {
            viajes.ViajeId = viajes.Rodal + viajes.N_Viaje.ToString() + viajes.FechaIngreso.Month.ToString() + "/" + viajes.FechaIngreso.Day.ToString() + "/" + viajes.FechaIngreso.Year.ToString();

            if (ModelState.IsValid)
            {
                _context.Add(viajes);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return PartialView("/Views/Viajes/_ViajesCreate.cshtml", viajes);
            }
            viajes.Nucleos = GetNucleos();
            viajes.Fincas = GetFincas();
            viajes.Rodales = GetRodales();
            return PartialView("/Views/Viajes/_ViajesCreate.cshtml", viajes);
        }

        public async Task<IActionResult> GetViaje(int id)
        {
            //GetSelectedListItem();
            var model = await _context.Viajes.SingleOrDefaultAsync(m => m.Id == id);
            return PartialView("/Views/Viajes/_ViajesEdit.cshtml",model);
        }


        public async Task<IActionResult> EditModal(int id, Viajes viajes)
        {
            if (id != viajes.Id)
            {

EquiforestWebApp/Views/Viajes/Create.cshtml
@model EquiforestWebApp.Models.Viajes

@{
    ViewData["Title"] = "Crear Viaje";
}

<h2>Crear Viaje</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nucleo" class="control-label"></label>
                @*<input asp-for="Nucleo" class="form-control" />*@
                <select asp-for="Nucleo" class="form-control" asp-items="ViewBag.Nucleos" name="Nucleo">
                    <option selected="selected" value="">Seleccionar el nucleo</option>
                </select>
                <span asp-validation-for="Nucleo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Finca" class="control-label"></label>
                @*<input asp-for="Finca" class="form-control" />*@
                <select asp-for="Finca" class="form-control" asp-items="ViewBag.Fincas" name="Finca">
                    <option selected="selected" value="">Seleccionar la finca</option>
                </select>
                <span asp-validation-for="Finca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rodal" class="control-label"></label>
                @*<input asp-for="Rodal" class="form-control" />*@
                <select asp-for="Rodal" class="form-control" asp-items="ViewBag.Rodales" name="Rodal">
                    <option selected="selected" value="s">Seleccionar el rodal</option>
                </select>
                <span asp-validation-for="Rodal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" name="FechaIngreso"/>
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ubicacion" class="control-label"></label>
                <input asp-for="Ubicacion" class="form-control" name="Ubicacion"/>
                <span asp-validation-for="Ubicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="N_Viaje" class="control-label"></label>
                <input asp-for="N_Viaje" class="form-control" />
                <span asp-validation-for="N_Viaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EquiforestWebApp/Views/Viajes/Delete.cshtml
@model EquiforestWebApp.Models.Viajes

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Viajes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nucleo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nucleo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Finca)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Finca)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rodal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rodal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.N_Viaje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.N_Viaje)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ViajeId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EquiforestWebApp/Views/Viajes/Details.cshtml
@model EquiforestWebApp.Models.Viajes

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Viajes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Nucleo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nucleo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Finca)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Finca)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Rodal)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Rodal)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FechaIngreso)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FechaIngreso)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Ubicacion)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Ubicacion)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.N_Viaje)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.N_Viaje)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ViajeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EquiforestWebApp/Views/Viajes/Edit.cshtml
@model EquiforestWebApp.Models.Viajes

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Viajes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="ViajeId" />
            <div class="form-group">
                <label asp-for="Nucleo" class="control-label"></label>
                <input asp-for="Nucleo" class="form-control" />
                <span asp-validation-for="Nucleo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Finca" class="control-label"></label>
                <input asp-for="Finca" class="form-control" />
                <span asp-validation-for="Finca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rodal" class="control-label"></label>
                <input asp-for="Rodal" class="form-control" />
                <span asp-validation-for="Rodal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ubicacion" class="control-label"></label>
                <input asp-for="Ubicacion" class="form-control" />
                <span asp-validation-for="Ubicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="N_Viaje" class="control-label"></label>
                <input asp-for="N_Viaje" class="form-control" />
                <span asp-validation-for="N_Viaje" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

EquiforestWebApp/Views/Viajes/Index.cshtml
@model PaginatedList<EquiforestWebApp.Models.ViajesGroup>

@{
    ViewData["Title"] = "Detalle de cosecha";
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}


<script src="~/lib/jquery/dist/jquery.js"></script>
<script type="text/javascript">
    // Handle "Edit Person" button click.
    // This will make an ajax call, get information for person,
    // put it all in the modal and display it
    $(document).on('click', '#btn-trigger-modal', function () {
        var viajeId = $(this).data('id');
        $.ajax({
            url: '/Viajes/OnGetViajesCreate',
            type: 'GET',
            data: { id: viajeId },
            success: function (data) {
                $('#div_content').html(data);
//                $('#nucleo').text(data.nucleo);
                $('#exampleModal').modal('show');
            }
        });
    });

    // Handle submitting of new information for Person.
    // This will attempt to save new info
    // If save was successful, it will close the Modal and reload page to see updated info
    // Otherwise it will only reload contents of the Modal
    $(document).on('click', '#saveModal', function () {
        var self = $(this);
        var actionUrl = '/Viajes/OnPostViajesCreate';
        var dataToSend = self.parents('.modal').find('form').serialize();

        $.post(actionUrl, dataToSend).done(function (data) {
            //console.log(data);
            $('#div_content').html(data);
            var newBody = $('.modal-body', data);
            var valValid = $('#div_content').find('[name="IsValid"]').val();
            var isValid = valValid == 'True';
                //newBody.find('[name="IsValid"]').val() == 'True';

            if (isValid) {
                $('#exampleModal').modal('hide');
                location.reload(false);
            }
        });


        @*$.ajax({
            url: '/Viajes/EditModal/' + $('#Id').val(),
            type: 'POST',
            contentType: 'application/json; charset=utf-8',
            data: self.parents('.modal').find('form').serialize(),
            success: function (data) {
                if (data.success == true) {
                    $('#modal-person').modal('hide');
                    location.reload(false)
                } else {
                    $('#modal-person').html(data);
                }
            }
        });*@
    });
</script>


<h3>Detalle de Cosecha</h3>
<div class="row">
    <div class="col-md-6 col-xs-4">
        <form asp-controller="Viajes" asp-action="Index" method="get">
            <div class="form form-inline">
                <p>
                    <input type="hidden" name="pageNumber" value="1" />
                    <input type="date" class="form-control" name="fecini" value="@ViewData["FecIni"]" />
                    <input type="date" class="form-control" name="fecfin" value="@ViewData["FecFin"]" />
                    <select asp-items="ViewBag.Rodales" name="Rodal" class="form-control">
                        <option selected="selected" value="@ViewBag.RodalSelected">@ViewBag.RodalSelected</option>
                    </select>
                    <input type="submit" value="Filtrar" class="btn btn-default" />
                </p>
            </div>
        </form>
    </div>
    <div>
        <table>
            <tbody>
                <tr>
                    <td>
                        <form asp-action="ImportFromExcel" asp-route-id="1" method="post" enctype="multipart/form-data">
                            <label class="control-label">Excel File</label>
                            <input type="file" class="" name="theExcel" />
                            <input type="submit" value="Subir Datos" />
                        </form>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    
</div>
@*<p>
        <a href="#" id="btn-trigger-modal">Create New</a>
    </p>*@
<table class="table table-condensed">
    <thead>
        <tr>
            <th>
                Nucleo
            </th>
            <th>
                Finca
            </th>
            <th>
                Rodal
            </th>
            <th>
                Fecha
            </th>
            <th>
                Ubicacion
            </th>
            <th>
                N_Viaje
            </th>
            <th>
                No. Trozas "C"
            </th>
            <th>
                Clasificación
            </th>
            <th>
                Cantidad
            </th>
            <th>
                Circunferencia (Avg)
            </th>
            <th>
                Largo (Avg)
            </th>
            <th>
                Volumen (Sum)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nucleo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Finca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rodal)
            </td>
            <td>
                @item.Fecha.ToShortDateString()
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ubicacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.N_Viaje)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NoTrozasC)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Clasificacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td>
                @string.Format("{0:#,0.00}", item.Circunferencia)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Longitud)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Volumen)
            </td>

            @*              <td>
            <a href="#" id="btn-trigger-modal" data-id="@item.Id">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.ViajeId">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.ViajeId">Delete</a>
        </td>*@
        </tr>
        }
    </tbody>
</table>


<div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Editar Viajes</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body" id="div_content">
                    <!--<partial name="_ViajesEdit.cshtml" />-->
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-fecini="@ViewData["FecIni"]"
           asp-route-fecfin="@ViewData["FecFin"]"
           class="btn btn-default @prevDisabled">
            Previous
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-fecini="@ViewData["FecIni"]"
           asp-route-fecfin="@ViewData["FecFin"]"
           class="btn btn-default @nextDisabled">
            Next
        </a>
        <span>Pag. @Model.PageIndex / @Model.TotalPages</span>
        <a asp-area="" asp-controller="Viajes" asp-action="Index" asp-route-id="1" asp-route-fecini="@ViewData["FecIni"]" asp-route-fecfin="@ViewData["FecFin"]" asp-route-download="true" class="btn btn-info">Descargar</a>
    </div>
</div>

EquiforestWebApp/Views/Viajes/_ViajesCreate.cshtml
@model EquiforestWebApp.Models.Viajes

<div class="row">
    <div class="col-md-4">
        <form asp-action="ViajesCreate">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
            <div class="form-group">
                <label asp-for="Nucleo" class="control-label">Nucleo</label>
                <select asp-for="Nucleo" asp-items="Model.Nucleos" class="form-control" name="Nucleo">
                    <option selected="selected" value="@Model.Nucleo">@Model.Nucleo</option>
                </select>
                <span asp-validation-for="Nucleo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Finca" class="control-label"></label>
                <select asp-for="Finca" asp-items="Model.Fincas" class="form-control" name="Finca">
                    <option selected="selected" value="@Model.Finca">@Model.Finca</option>
                </select>
                <span asp-validation-for="Finca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rodal" class="control-label"></label>
                <select asp-for="Rodal" asp-items="Model.Rodales" class="form-control" name="Rodal">
                    <option selected="selected" value="@Model.Rodal">@Model.Rodal</option>
                </select>
                <span asp-validation-for="Rodal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaIngreso" class="control-label"></label>
                <input asp-for="FechaIngreso" class="form-control" name="FechaIngreso" />
                <span asp-validation-for="FechaIngreso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Ubicacion" class="control-label"></label>
                <input asp-for="Ubicacion" class="form-control" name="Ubicacion" />
                <span asp-validation-for="Ubicacion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="N_Viaje" class="control-label"></label>
                <input asp-for="N_Viaje" class="form-control" name="N_Viaje" />
                <span asp-validation-for="N_Viaje" class="text-danger"></span>
            </div>
        </form>
    </div>
</div>

<div class="modal-footer">
    <button type="button" class="btn btn-primary" id="saveModal">Save</button>
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
</div>